services:
  mysql-service:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lldb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springboot-mysql-net

  backend:
    image: 2300090230/ecom-backend:latest
    container_name: springboot
    ports:
    
      - "30025:2000"
    depends_on:
      - mysql-service
    restart: on-failure
    networks:
      - springboot-mysql-net

  frontend:
    image: 2300090230/ecom-frontend:latest
    container_name: react
    ports:
      - "30080:80"
    depends_on:
      - backend
    restart: on-failure
    networks:
      - springboot-mysql-net

volumes:
  mysql_data:

networks:
  springboot-mysql-net: